added more cases and functionalities
windup/windup-ui-tests pull request #14
Opened 2023-02-07 13:51 UTC by stillalearner

2023-02-07 18:36 UTC, sshveta requested changes
@stillalearner Can you please add to the description which all test cases this PR is automating .

2023-02-07 18:36 UTC, sshveta commented on cypress/e2e/models/analysis.ts
> +    // Function to Search an analysis by id
We can move this comment inside the method .

2023-02-07 18:36 UTC, sshveta commented on cypress/e2e/models/analysis.ts
> +    //TODO: Function to delete latest analysis
This comment can be removed as it is implemented.

2023-02-07 18:36 UTC, sshveta commented on cypress/e2e/models/analysis.ts
> +    searchLatest(): void {
What is the test case here ?  It will search for latest analysis ?

2023-02-07 18:36 UTC, sshveta commented on cypress/e2e/tests/analysis.test.ts
> +        analysis.searchLatest();
To test search feature we should create atleast two analysis and then search with different Id or status .

2023-02-07 18:36 UTC, sshveta commented on cypress/e2e/tests/analysis.test.ts
> +    it("Sort Report with Name/Story Points", function () {
Let's move this test case to report.test.ts where we can add more tests around reports.

2023-02-09 12:20 UTC, stillalearner commented on cypress/e2e/tests/analysis.test.ts
> +        analysis.searchLatest();
@sshveta yes, earlier i tried to run 2 analysis and then search with the ID lets say the second one. But the issue is in MTR, analysis ID does not start from 1 for every project. It keeps increasing the count and after running the analysis, one doesn't know the ID to search.

So, here i am running the analysis 2 times, and taking the latest analysis ID and searching it from the search box and making sure that only 1 analysis is visible after the search.

2023-02-11 15:53 UTC, stillalearner commented on cypress/e2e/models/analysis.ts
> +    //TODO: Function to delete latest analysis
done

2023-02-11 15:53 UTC, stillalearner commented on cypress/e2e/models/analysis.ts
> +    // Function to Search an analysis by id
done

2023-02-11 15:55 UTC, stillalearner commented on cypress/e2e/models/analysis.ts
> +    searchLatest(): void {
This is the helper function to "Search analysis" test case explained in the other comment. It gets the ID for the latest analysis and then search it.

2023-02-11 15:56 UTC, stillalearner commented on cypress/e2e/tests/analysis.test.ts
> +    it("Sort Report with Name/Story Points", function () {
done

2023-02-13 05:26 UTC, sshveta approved these changes

2023-02-13 05:27 UTC, sshveta commented
Looks Good @stillalearner . 
Can you make sure these test cases are added in Polarion as well.

2023-02-13 05:27 UTC, merged