automated mta-239
windup/windup-ui-tests pull request #21
Opened 2023-02-27 09:47 UTC by stillalearner

2023-02-27 16:38 UTC, sshveta requested changes

2023-02-27 16:38 UTC, sshveta commented on cypress/utils/utils.ts
> +export function isMTROnOCP(): boolean {
Isn't this function same as isInstalledOnOCP() ?

2023-02-27 16:38 UTC, sshveta commented on cypress/e2e/tests/features.test.ts
> +        cy.contains("span", "azure-appservice", { timeout: 120 * SEC }).should("not.exist");
azure-app service is present in UI .
azure-aks is not .

2023-02-28 12:56 UTC, stillalearner commented on cypress/utils/utils.ts
> +export function isMTROnOCP(): boolean {
this one is different. It is used for checking if downstream is installed on OCP.

while the old function checks whether the installation is standalone OR on OCP

2023-02-28 12:56 UTC, stillalearner commented on cypress/e2e/tests/features.test.ts
> +        cy.contains("span", "azure-appservice", { timeout: 120 * SEC }).should("not.exist");
added comment explaining the reason.

2023-02-28 14:42 UTC, sshveta approved these changes

2023-02-28 14:42 UTC, merged