[RFR] Fix jenkins chrome crash issue
windup/windup-ui-tests pull request #34
Opened 2023-04-14 10:00 UTC by stillalearner

2023-04-14 15:18 UTC, sshveta requested changes

2023-04-14 15:18 UTC, sshveta commented on cypress/e2e/models/projects.ts
> +        clickByText(primaryButton, next);
why are we clicking twice ?

2023-04-14 15:18 UTC, sshveta commented on cypress/e2e/tests/analysis.test.ts
> +describe(["tier1"], "Analysis2", function () {
Why Anlaysis 2?

We can name this standard analysis tests

2023-04-14 15:18 UTC, sshveta commented on cypress/e2e/tests/targets.test.ts
> +describe(["tier1"], "Analysis", function () {
And this one we can name 
"analysis on different targets"

2023-04-17 06:21 UTC, stillalearner commented on cypress/e2e/tests/analysis.test.ts
> +describe(["tier1"], "Analysis2", function () {
done

2023-04-17 06:21 UTC, stillalearner commented on cypress/e2e/tests/targets.test.ts
> +describe(["tier1"], "Analysis", function () {
done

2023-04-17 17:03 UTC, sshveta approved these changes

2023-04-17 17:03 UTC, merged